run:
	g++ -g -O2 -std=c++11 -pthread -march=native utils.cpp primes.cpp rsa.cpp main.cpp -o main -lntl -lgmp -lm && ./main

time:
	g++ -g -O2 -std=c++11 -pthread -march=native utils.cpp primes.cpp rsa.cpp testTime.cpp -o testTime -lntl -lgmp -lm && ./testTime
